source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'Swimmer' do
	pod 'Alamofire'
	pod 'SnapKit'
	pod 'SDWebImage'
	pod 'IQKeyboardManager'
	pod 'MBProgressHUD'
end